### ISSUE TITLE
Safari 브라우저 폰트 깨짐 현상

### ISSUE THREAD

**Issue by YeonghyeonKO** [wafflestudio/wafflestudio.com#46]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/46114393/157603512-17e2c006-a06a-4759-82af-3620ba43c2a4.png">

**Comment by YeonghyeonKO** [comment]
@woohm402 구버전이었군요... 신버전은 도메인 주소 나왔나요?

**Comment by woohm402** [comment]
@YeonghyeonKO 신버전은 https://dev.wafflestudio.com 에서 개발 진행중입니다 :)

**Comment by woohm402** [comment]
재현되지 않아 close합니다. 재현되면 reopen 처리하겠습니다.
